/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import Controller.Controller;
import classes.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author inter-telco
 */
public class Main extends javax.swing.JFrame {

    Map<Integer, String> index;
    int idClient = -1, code = -1, idRequest;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        index = new HashMap<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Clientes = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TypeClient = new javax.swing.JComboBox<>();
        Name = new javax.swing.JLabel();
        FirstNameInput = new javax.swing.JTextField();
        Second_id = new javax.swing.JLabel();
        SecondLastName = new javax.swing.JTextField();
        SecondFirstname = new javax.swing.JTextField();
        money = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FirstLastNameInput = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientList = new javax.swing.JList<>();
        CreateClient = new javax.swing.JButton();
        UpdateClient = new javax.swing.JButton();
        DeleteClient = new javax.swing.JButton();
        LoadClient = new javax.swing.JButton();
        CCLabel = new javax.swing.JLabel();
        CC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SelectedClient = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        addRequest = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        supplier = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        quantity = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        addProduct = new javax.swing.JButton();
        buyingBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        productList = new javax.swing.JList<>();
        LoadProduct = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();
        deleteProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        SelectedToPay = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        clientMoney = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        destiny = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        payButton = new javax.swing.JButton();
        rebootCart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Tipo:");

        TypeClient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Jurídico" }));
        TypeClient.setToolTipText("");
        TypeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeClientActionPerformed(evt);
            }
        });

        Name.setText("Nombres");

        FirstNameInput.setText("*");
        FirstNameInput.setToolTipText("");

        Second_id.setText("Apellidos");

        SecondLastName.setToolTipText("");
        SecondLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecondLastNameActionPerformed(evt);
            }
        });

        SecondFirstname.setToolTipText("");

        money.setText("*");
        money.setToolTipText("");

        jLabel5.setText("Saldo");

        jLabel11.setText("Dirección");

        FirstLastNameInput.setText("*");
        FirstLastNameInput.setToolTipText("");
        FirstLastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstLastNameInputActionPerformed(evt);
            }
        });

        jLabel14.setText("Email");

        email.setText("*");
        email.setToolTipText("");

        jLabel15.setText("Teléfono");

        address.setText("*");
        address.setToolTipText("");

        phone.setText("*");
        phone.setToolTipText("");

        jLabel17.setText("Lista: ");

        jScrollPane1.setViewportView(clientList);

        CreateClient.setText("Crear");
        CreateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateClientActionPerformed(evt);
            }
        });

        UpdateClient.setText("Actualizar");
        UpdateClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateClientActionPerformed(evt);
            }
        });

        DeleteClient.setText("Borrar");
        DeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteClientActionPerformed(evt);
            }
        });

        LoadClient.setText("Cargar");
        LoadClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadClientActionPerformed(evt);
            }
        });

        CCLabel.setText("C.C.");

        CC.setText("*");
        CC.setToolTipText("");
        CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(TypeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name)
                                    .addComponent(Second_id))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(FirstLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SecondFirstname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(SecondLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CCLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CC))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addGap(18, 18, 18)
                                            .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(CreateClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdateClient)
                                .addGap(35, 35, 35)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jLabel14))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel15)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(phone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(DeleteClient)
                                .addGap(18, 18, 18)
                                .addComponent(LoadClient)))))
                .addGap(178, 178, 178))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TypeClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CCLabel)
                    .addComponent(CC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstLastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Second_id)
                    .addComponent(SecondLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(money, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateClient)
                    .addComponent(UpdateClient)
                    .addComponent(DeleteClient)
                    .addComponent(LoadClient))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Clientes.addTab("Clientes", jPanel1);

        jLabel2.setText("Cliente:");

        SelectedClient.setText("No seleccionado");
        SelectedClient.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                SelectedClientComponentShown(evt);
            }
        });

        jLabel7.setText("Carrito de compras");

        jScrollPane2.setViewportView(requestList);

        jLabel8.setText("Lista de productos");

        addRequest.setText("+");
        addRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRequestActionPerformed(evt);
            }
        });

        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel9.setText("marca");

        supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierActionPerformed(evt);
            }
        });

        jLabel10.setText("Proveedor");

        jLabel12.setText("Descripción");

        jLabel13.setText("precio");

        jLabel18.setText("Cantidad");

        description.setColumns(20);
        description.setRows(5);
        jScrollPane4.setViewportView(description);

        addProduct.setText("Añadir producto");
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        buyingBtn.setText("Comprar");
        buyingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyingBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(productList);

        LoadProduct.setText("Cargar");
        LoadProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadProductActionPerformed(evt);
            }
        });

        updateProduct.setText("Actualizar");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });

        deleteProduct.setText("Borrar");
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SelectedClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(13, 13, 13)
                                        .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel10))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(addProduct)
                .addGap(18, 18, 18)
                .addComponent(updateProduct)
                .addGap(18, 18, 18)
                .addComponent(deleteProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LoadProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buyingBtn)))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(SelectedClient)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addRequest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProduct)
                    .addComponent(buyingBtn)
                    .addComponent(LoadProduct)
                    .addComponent(updateProduct)
                    .addComponent(deleteProduct))
                .addGap(36, 36, 36))
        );

        Clientes.addTab("Productos", jPanel2);

        jLabel20.setText("Cliente:");

        SelectedToPay.setText("No seleccionado");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Detalle", "Cantidad", "Valor", "Total", "Fecha", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(Table);

        clientMoney.setText("0$");

        jLabel23.setText("Saldo");

        jLabel24.setText("Destino");

        destiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinyActionPerformed(evt);
            }
        });

        jLabel25.setText("Compañia de envios");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UPS", "FDX", "Deprisa", "TCC", "Servientrega", "InterRapidisimo", "Coordinadora", "4-72", "FedEx" }));

        payButton.setText("Pagar");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        rebootCart.setText("Vaciar Carrito");
        rebootCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebootCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel23)
                .addGap(26, 26, 26)
                .addComponent(clientMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(26, 26, 26)
                .addComponent(SelectedToPay)
                .addGap(25, 25, 25))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(destiny, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(payButton))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(25, 25, 25)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rebootCart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(SelectedToPay)
                    .addComponent(jLabel23)
                    .addComponent(clientMoney))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(destiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payButton)
                    .addComponent(rebootCart))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        Clientes.addTab("Pedidos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeClientActionPerformed
        // TODO add your handling code here
        Controller controller = new Controller();

        this.phone.setText("*");
        this.email.setText("*");
        this.money.setText("*");
        this.address.setText("*");
        this.FirstNameInput.setText("*");
        this.SecondFirstname.setText("");
        this.FirstLastNameInput.setText("*");
        this.SecondLastName.setText("");
        this.CC.setEnabled(true);
        Color color = new Color(0, 0, 0);
        this.CCLabel.setForeground(color);
        this.clientList.removeAll();
        this.clientList.revalidate();

        if (this.TypeClient.getSelectedItem() == "Jurídico") {
            this.address.getText();

            this.Name.setText("Razón Social");
            this.Second_id.setText("NIT");
            this.SecondFirstname.setEnabled(false);
            this.SecondFirstname.setText(" ");
            this.SecondLastName.setEnabled(false);
            this.CC.setEnabled(false);
            color = new Color(242, 242, 242);
            this.CCLabel.setForeground(color);
            this.SecondLastName.setText("");
            this.clientList.setModel(controller.createClientJlistModel("Jurídico"));

        } else {
            this.CC.setEnabled(true);
            this.Name.setText("Nombres");
            this.Second_id.setText("Apellidos");
            this.SecondFirstname.setEnabled(true);
            this.SecondLastName.setEnabled(true);
            this.clientList.setModel(controller.createClientJlistModel("Natural"));

        }
        this.productList.setModel(controller.createProductJlistModel());
    }//GEN-LAST:event_TypeClientActionPerformed

    private void destinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinyActionPerformed

    private void SecondLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecondLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecondLastNameActionPerformed

    private void CreateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateClientActionPerformed
        // TODO add your handling code here:

        Controller controller = new Controller();

        String adr = this.address.getText();
        String phoneNumber = this.phone.getText();
        String mail = this.email.getText();
        String coins = this.money.getText();
        String firstName = this.FirstNameInput.getText();
        String secondName = this.SecondFirstname.getText();
        String firstLastName = this.FirstLastNameInput.getText();
        String secondLastName = this.SecondLastName.getText();
        String cc = this.CC.getText();

        if ("".equals(cc) || "".equals(adr) || "".equals(phoneNumber) || "".equals(mail) || "".equals(coins) || "".equals(firstName) || "".equals(firstLastName)) {
            JOptionPane.showMessageDialog(rootPane, "Los campos con * son obligatorios.");
        } else {

            if (this.TypeClient.getSelectedItem() == "Jurídico") {

                controller.addClient(firstName, firstLastName, adr, mail, Double.parseDouble(coins), phoneNumber);
                this.TypeClient.setSelectedIndex(1);
            } else {

                controller.addClient(cc, firstName, secondName, firstLastName, secondLastName, adr, mail, Double.parseDouble(coins), phoneNumber);
                this.TypeClient.setSelectedIndex(0);
            }

        }
    }//GEN-LAST:event_CreateClientActionPerformed

    private void LoadClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadClientActionPerformed
        // TODO add your handling code here:

        Controller controller = new Controller();
        int i = this.clientList.getSelectedIndex();
        String clientName = "";
        if (i == -1) {
            JOptionPane.showMessageDialog(null, "No hay elemento seleccionado");
        } else {

            String[] rowClientList = this.clientList.getSelectedValue().split("\\.");
            clientName += rowClientList[1];
            if (rowClientList.length > 2) {
                for (int j = 2; j < rowClientList.length; j++) {
                    clientName += "." + rowClientList[j];
                }
            }
            this.idClient = Integer.parseInt(rowClientList[0]);
            DefaultTableModel tableModel = controller.createTableModelOfRequestData(idClient);
            DefaultListModel listModel = controller.createRequestModel(idClient);
            this.Table.setModel(tableModel);
            this.requestList.setModel(listModel);
            this.SelectedClient.setText(clientName);
            this.SelectedToPay.setText(clientName);
            if (this.TypeClient.getSelectedItem() == "Jurídico") {
                Legal client = controller.getLegalData(idClient);
                this.phone.setText(client.getPhoneNumber());
                this.email.setText(client.getEmail());
                this.money.setText(Double.toString(client.getMoney()));
                this.clientMoney.setText(Double.toString(client.getMoney()) + "$ pesos");
                this.address.setText(client.getAddress());
                this.FirstNameInput.setText(client.getBusinessName());
                this.SecondFirstname.setText(" ");
                this.FirstLastNameInput.setText(client.getNIT());
                this.SecondLastName.setText(" ");
            } else {
                Natural client = controller.getNaturalData(idClient);
                this.CC.setText(client.getCC());
                this.phone.setText(client.getPhoneNumber());
                this.email.setText(client.getEmail());
                this.money.setText(Double.toString(client.getMoney()));
                this.clientMoney.setText(Double.toString(client.getMoney()) + "$ pesos");
                this.address.setText(client.getAddress());
                this.FirstNameInput.setText(client.getFirstName());
                this.SecondFirstname.setText(client.getSecondName());
                this.FirstLastNameInput.setText(client.getFirstLastName());
                this.SecondLastName.setText(client.getSecondLastName());
            }

        }
    }//GEN-LAST:event_LoadClientActionPerformed

    private void DeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteClientActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        int i = this.clientList.getSelectedIndex();
        String[] rowClientList = this.clientList.getSelectedValue().split("\\.");
        this.idClient = Integer.parseInt(rowClientList[0]);
        if (i == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado algún cliente.");
        } else {
            if (controller.deletedClient(idClient)) {
                this.TypeClient.setSelectedItem(this.TypeClient.getSelectedItem());
                JOptionPane.showMessageDialog(null, "Cliente eliminado con éxito");
            } else {

                JOptionPane.showMessageDialog(rootPane, "Cliente no encontrado en la base de datos.");
            }

        }

    }//GEN-LAST:event_DeleteClientActionPerformed

    private void UpdateClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateClientActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.clientList.getSelectedValue().split("\\.");
        this.idClient = Integer.parseInt(rowClientList[0]);

        String adr = this.address.getText();
        String phoneNumber = this.phone.getText();
        String mail = this.email.getText();
        String coins = this.money.getText();
        String firstName = this.FirstNameInput.getText();
        String secondName = this.SecondFirstname.getText();
        String firstLastName = this.FirstLastNameInput.getText();
        String secondLastName = this.SecondLastName.getText();
        String cc = this.CC.getText();

        if ("".equals(cc) || "".equals(adr) || "".equals(phoneNumber) || "".equals(mail) || "".equals(coins) || "".equals(firstName) || "".equals(firstLastName)) {
            JOptionPane.showMessageDialog(rootPane, "Los campos con * son obligatorios.");
        } else {

            if (this.TypeClient.getSelectedItem() == "Jurídico") {

                controller.updateClient(firstName, firstLastName, adr, mail, idClient, Double.parseDouble(coins), phoneNumber);
                this.TypeClient.setSelectedIndex(1);
            } else {

                controller.updateClient(cc, firstName, secondName, firstLastName, secondLastName, adr, idClient, mail, Double.parseDouble(coins), phoneNumber);
                this.TypeClient.setSelectedIndex(0);
            }

        }
    }//GEN-LAST:event_UpdateClientActionPerformed

    private void supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierActionPerformed

    private void SelectedClientComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_SelectedClientComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedClientComponentShown

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();

        String br = this.brand.getText();
        String sup = this.supplier.getText();
        String value = this.price.getText();
        String quant = this.quantity.getText();
        String desc = this.description.getText();

        if ("".equals(br) || "".equals(sup) || "".equals(value) || "".equals(quant) || "".equals(desc)) {
            JOptionPane.showMessageDialog(rootPane, "Todos lo campos son obligatorios.");
        } else {

            controller.addProduct(br, sup, value, quant, desc);
            this.productList.setModel(controller.createProductJlistModel());
        }
    }//GEN-LAST:event_addProductActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.productList.getSelectedValue().split("\\.");
        this.code = Integer.parseInt(rowClientList[0]);

        String br = this.brand.getText();
        String sup = this.supplier.getText();
        String value = this.price.getText();
        String quant = this.quantity.getText();
        String desc = this.description.getText();

        if ("".equals(br) || "".equals(sup) || "".equals(value) || "".equals(quant) || "".equals(desc)) {
            JOptionPane.showMessageDialog(rootPane, "Todos lo campos son obligatorios.");
        } else {

            controller.updateProduct(this.code, br, sup, value, quant, desc);
            this.productList.setModel(controller.createProductJlistModel());

        }
    }//GEN-LAST:event_updateProductActionPerformed

    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.productList.getSelectedValue().split("\\.");
        this.code = Integer.parseInt(rowClientList[0]);

        if (this.productList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado algún producto.");
        } else {
            if (controller.deletedProduct(this.code)) {
                this.productList.setModel(controller.createProductJlistModel());
                JOptionPane.showMessageDialog(null, "Producto eliminado con éxito");
                this.code = -1;
            } else {

                JOptionPane.showMessageDialog(rootPane, "producto no encontrado en la base de datos.");
            }

        }
    }//GEN-LAST:event_deleteProductActionPerformed

    private void LoadProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadProductActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.productList.getSelectedValue().split("\\.");
        this.code = Integer.parseInt(rowClientList[0]);
        if (this.productList.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "No hay elemento seleccionado");
        } else {

            Product product = controller.getProductData(this.code);
            this.brand.setText(product.getBrand());
            this.supplier.setText(product.getSupplier());
            this.price.setText(Double.toString(product.getPrice()));
            this.quantity.setText(Integer.toString(product.getQuantity()));
            this.description.setText(product.getDescription());

        }
    }//GEN-LAST:event_LoadProductActionPerformed

    private void addRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRequestActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.productList.getSelectedValue().split("\\.");
        this.code = Integer.parseInt(rowClientList[0]);
        List<String> selectedValueList = this.productList.getSelectedValuesList();
        ArrayList<Integer> indexs = new ArrayList<>();
        selectedValueList.forEach(element -> {
            indexs.add(Integer.parseInt(element.split("\\.")[0]));

        });
        if (this.code == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto para poder agregarlo en la lista de peticiones");
        } else {
            DefaultListModel model = controller.createRequestsList(indexs, idClient, false);
            this.requestList.setModel(model);
        }

    }//GEN-LAST:event_addRequestActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        String[] rowClientList = this.productList.getSelectedValue().split("\\.");
        this.code = Integer.parseInt(rowClientList[0]);
        List<String> selectedValueList = this.productList.getSelectedValuesList();
        ArrayList<Integer> productIndexs = new ArrayList<>();
        selectedValueList.forEach(element -> {
            productIndexs.add(Integer.parseInt(element.split("\\.")[0]));
        });

        if (this.code == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto para poder agregarlo en la lista de peticiones");
        } else {
            DefaultListModel model = controller.createRequestsList(productIndexs, idClient, true);
            this.requestList.setModel(model);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void buyingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyingBtnActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();

        if (idClient == -1) {
            JOptionPane.showMessageDialog(null, "Para solicitar la compra debes seleccionar un cliente.");
        } else {
            DefaultTableModel model = controller.createTableModelOfRequestData(idClient);
            this.Table.setModel(model);
            JOptionPane.showMessageDialog(rootPane, "!Compra gestionada exitosamente!. Pase a la pestaña de pedidos para especificar destino y pagar.");
        }
        //
    }//GEN-LAST:event_buyingBtnActionPerformed

    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
        // TODO add your handling code here:
        if (this.destiny.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Olvidaste colocar el destino");
        } else {
            Controller controller = new Controller();
            Double cltMoney = Double.parseDouble(this.clientMoney.getText().substring(0, this.clientMoney.getText().length() - 7));
            Double totalToPay = controller.getTotalToPay(idClient);
            if (cltMoney - totalToPay < 0) {
                JOptionPane.showMessageDialog(rootPane, "No cuenta con suficiente dinero para efectuar el pago.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Su compra fue: \n\n\t" + controller.getBill(idClient));
                controller.updateMoney(idClient, cltMoney - totalToPay);
                this.clientMoney.setText(Double.toString(cltMoney - totalToPay) + "$ pesos");
                DefaultTableModel model = controller.createTableModelOfRequestData(idClient);
                this.Table.setModel(model);
                controller.resetRequestList(idClient);
                DefaultListModel listModel = new DefaultListModel();
                this.requestList.setModel(listModel);
                controller.updateProductList(idClient);
                this.productList.setModel(controller.createProductJlistModel());
                Object columnas[] = {"ID", "Marca", "Detalle", "Cantidad", "Valor", "Total", "Fecha", "Estado"};
                model = new DefaultTableModel(columnas, 0);
                this.Table.setModel(model);
            }
        }

    }//GEN-LAST:event_payButtonActionPerformed

    private void rebootCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebootCartActionPerformed
        // TODO add your handling code here:
        Controller controller = new Controller();
        controller.resetRequestList(idClient);
        Object columnas[] = {"ID", "Marca", "Detalle", "Cantidad", "Valor", "Total", "Fecha", "Estado"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0);
        DefaultListModel listModel = new DefaultListModel();
        this.requestList.setModel(listModel);
        this.Table.setModel(model);

    }//GEN-LAST:event_rebootCartActionPerformed

    private void FirstLastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstLastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstLastNameInputActionPerformed

    private void CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CC;
    private javax.swing.JLabel CCLabel;
    private javax.swing.JTabbedPane Clientes;
    private javax.swing.JButton CreateClient;
    private javax.swing.JButton DeleteClient;
    private javax.swing.JTextField FirstLastNameInput;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JButton LoadClient;
    private javax.swing.JButton LoadProduct;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField SecondFirstname;
    private javax.swing.JTextField SecondLastName;
    private javax.swing.JLabel Second_id;
    private javax.swing.JLabel SelectedClient;
    private javax.swing.JLabel SelectedToPay;
    private javax.swing.JTable Table;
    private javax.swing.JComboBox<String> TypeClient;
    private javax.swing.JButton UpdateClient;
    private javax.swing.JButton addProduct;
    private javax.swing.JButton addRequest;
    private javax.swing.JTextField address;
    private javax.swing.JTextField brand;
    private javax.swing.JButton buyingBtn;
    private javax.swing.JList<String> clientList;
    private javax.swing.JLabel clientMoney;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField destiny;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField money;
    private javax.swing.JButton payButton;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField price;
    private javax.swing.JList<String> productList;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton rebootCart;
    private javax.swing.JList<String> requestList;
    private javax.swing.JTextField supplier;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables
}
